### ISSUE TITLE
Extend the log file highlighter to other formats (crm)

### ISSUE THREAD

**Issue by con-ssc** [emilast/vscode-logfile-highlighter#12]
First, there is in general onother culture format for time for example 2016-10-25 12:21:08.340 the delimiter is not always comma. 
Second, something like
[2016-10-25 12:21:17.105] Process: w3wp |Organization:2c451fe8-4e66-e311-b2c1-005056806411 |Thread:   11 |Category: Platform.Sql |User: b6da5baa-6c53-4c0d-81e2-0d0ec3b5f58c |Level: Error |ReqId: 9b2b1b3a-b532-4d51-8c9f-22045c47b2ae | BusinessProcessObject.ExecuteQuery  ilOffset = 0x4A
Does not match the log levels althought Error is in there as a single word. Do you only check on all caps?

**Comment by emilast** [comment]
Yes, it's all caps right now, in order to decrease the likelihood of accidentally highlighting words in the middle of sentences.

I'll fix the comma/dot issue in time formats, but will have to think about `Level: Error` etc. Is that prefix `Level: ` frequently occurring in log files? I haven't seen that before. Maybe it would be better to have user configuration of keywords as was suggested in a review comment on the marketplace.

**Comment by con-ssc** [comment]
Well in the log files I use often yes. I had to extend it to Level: because only Error would give too many matches.
I made a pull request for the changes already.
