### ISSUE TITLE
ERROR syntax color

### ISSUE THREAD

**Issue by k4nai** [emilast/vscode-logfile-highlighter#27]
Hi,

I contacted the dev who created Atom One Dark theme because of some color issues but I think the issue is in Log File Highlighter so I will try here instead.

WARNING syntaxes in .log files is shown as red color but ERROR messages is shown as GREEN.
![image](https://user-images.githubusercontent.com/18008933/30473313-4ceb83c0-9a00-11e7-9936-a1b2c1b7529c.png)

If I disable Log File Highlighter and only enable the theme it looks like this:
![image](https://user-images.githubusercontent.com/18008933/30473597-3efc6878-9a01-11e7-99f5-28850a9af367.png)

Is it possible to fix change the ERROR syntax so it is the same color as WARNING so I can use it together with the theme?

**Comment by emilast** [comment]
Hi,

It is correct that the colors are not optimal for all themes and I'm planning to change how the rendering is done in order to make it more robust. In the meantime, you can hack the extension a little bit.

Open the installed extension's .tmLanguage file (on Windows, it should be `%USERPROFILE%\.vscode\extensions\emilast.LogFileHighlighter-1.1.1\syntaxes\log.tmLanguage`)  and look for this section:

```
<!-- ERROR -->
<dict>
    <key>match</key>
    <string>\b(ERROR|FAILURE|FAIL)\b|(?i)\b(error)\:</string>

    <key>name</key>
    <string>string.regexp, strong</string>
</dict>
```

Change the second to last line to `<string>markup.deleted</string>` and restart VS Code. Warnings and errors should now be colored the same way until a new update to the exension is installed, which will overwrite the modifications.

Once I get some time to spend on this, I'll see if I can make the colors customizable more easily, other users have reported the same need.

Cheers,

Emil

**Comment by exxmen** [comment]
Thanks for this Emil. The workaround is useful only when using Atom One Dark theme though.

**Comment by emilast** [comment]
Hi guys,

I just put up version 1.2.0 in which you should be able to override the default colors. The readme describes how it's done. Hopefully it solves your problems.

/Emil

**Comment by exxmen** [comment]
great update Emil!!
