### ISSUE TITLE
Support JSON styled log files

### ISSUE THREAD

**Issue by jankap** [emilast/vscode-logfile-highlighter#333]
I'm working on log files that are structured as JSON objects, one per line, e.g.

```
{"time":"27-01-2022 16:41:23.382","level":"CRITICAL","logger":"MyApp","callstack":"TiltSensorCalibrationApp.TiltSensorCalibrationApp","message":"Error using (line 66)\nInput Parsing Error\n\nCaused by:\n    Error using jsondecode\n    JSON syntax error at line 1, column 1 (character 1): expected value but found 'asdf'."}
{"time":"27-01-2022 16:44:03.062","level":"CRITICAL","logger":"MyApp","callstack":"TiltSensorCalibrationApp.TiltSensorCalibrationApp","message":"Error using (line 66)\nInput Parsing Error\n\nCaused by:\n    Error using jsondecode\n    JSON syntax error at line 1, column 1 (character 1): expected value but found 'asdf'."}
```

It might be interpreted as tabular data (as long as the format remains the same of course). Do you see any chance to support parsing that format?

Thank you very much!

**Comment by emilast** [comment]
Unfortunately I can't see a way forward here with the way the extension is built, since all data will be treated as strings when it's enclosed with quotes. What feature would be most interesting to get?

However, since the data is JSON fragments it should be possible to transform this kind of file into some kind of table formats relatively easily, but that would be outside the scope of this extension. Something like https://jsongrid.com/ might help:
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/2369639/151669633-e1b5a581-3e1c-43f3-a5e2-8a8c678aadf6.png">

For that to work, you'd probably need to manually touch up the log files so that they're valid JSON documents.

**Comment by lonix1** [comment]
In structured logging, the logs are meant for ingestion by automated services and so are hard to read by humans - hence the ugly json shown in the OP's example. But it's nonetheless useful to consult such logs during development anyway - so I also was hoping for this feature.

Are you aware of a `jsongrid` tool that can be used inside vscode? I'm asking because you know way more about this than the rest of us (since you maintain a logging extension :smile:).

BTW, I use the extension for other purposes too, and it's great - thanks for making it!

**Comment by lonix1** [comment]
@jankap Did you find another way?

**Comment by emilast** [comment]
> @emilast In structured logging, the logs are meant for ingestion by automated services and so are hard to read by humans - hence the ugly json shown in the OP's example. But it's nonetheless useful to consult such logs during development anyway - so I also was hoping for this feature.
> 
> Are you aware of a `jsongrid` tool that can be used inside vscode (or that an extension can "wrap" to provide this functionality)? I'm asking because you know way more about this than the rest of us (since you maintain a logging extension 😄).

No, I'm afraid I don't.

> BTW, I use the extension for other purposes too, and it's great - thanks for making it!

Thanks 😊
