### ISSUE TITLE
Re using log text mate grammar inside VS Code

### ISSUE THREAD

**Issue by sandy081** [emilast/vscode-logfile-highlighter#35]
@emilast I am a developer from VS Code. In last release (1.19) we added support for logging in VS Code. As a result of this VS Code generates log files which will be shown in Output channel and also can be opened in the editor.   

Now, we want to support syntax highlighting for these log files out of the box. I was looking for any existing syntax grammar for log files and I came across yours. So I would like to have following requests for you:

1. Can we reuse your grammar files for highlighting log files? We will update whenever you have fixes or enhancements

2. I see your extension is also doing the same. May I know if you are planning to add more functionalities to your extension other than highlighting? Not sure it is useful to have two things providing same feature.

Thanks

**Comment by emilast** [comment]
Hi @sandy081! Of course you may use whatever parts of my extension you feel is useful to include in the code base. It's nice that you mention it though, so that I'm aware that my simple extension might become obsolete :-)

I do have a few ideas and user suggestions (mostly around having custom keywords and also around visualization of the log event time stamps) that may be implemented in the future but currently my time is a limiting factor, so they're put on hold at the moment. So feel free to use what you want and I'll adapt when/if there are conflicts.

Good luck and feel free to keep me posted about how this progresses so I can adapt.

/Emil

**Comment by sandy081** [comment]
Thanks @emilast. Will import the grammar into our code and update it from your repo every milestone.
