### ISSUE TITLE
Is this extension deprecated after VSCode 1.20.0 release?

### ISSUE THREAD

**Issue by kenijo** [emilast/vscode-logfile-highlighter#44]
It looks like your code was integrated to the VS Code 1.20.0 release:
"Now you can see VS Code logs with syntax highlighting in the Output panel. Thanks to emilast for providing the grammar for syntax highlighting log files."

Does that mean your extension is now deprecated? Or does it provide more?

**Comment by HaaLeo** [comment]
No, version 2.0.0 supports analyzing the log file by showing you [how much time you have selected](https://github.com/emilast/vscode-logfile-highlighter#visualization-of-time-duration). And in the next release there will be something to [create custom log levels](https://github.com/HaaLeo/vscode-logfile-highlighter/tree/Enable-Custom-Log-Level#custom-log-levels) via the user configuration.

**Comment by kenijo** [comment]
Oh wahoo! That's pretty sweet, thanks for the clarrification.

**Comment by emilast** [comment]
It's true that they incorporated an earlier version of this extenstion into the VS Code 1.20 (January 2018) , but this extension will continue to be developed separately since it can be released much faster when something changes and also to add features such as the ones mentioned by @HaaLeo that not necessarily should go into the core VS Code code base.
