### ISSUE TITLE
Double file extention

### ISSUE THREAD

**Issue by twtterAntonyRus** [emilast/vscode-logfile-highlighter#465]
I have a log file named MySuperLog.txt.log and color highlighting didn't work.
After I change file name to MySuperLog.log - all works as expected.

**Comment by emilast** [comment]
Well, that should work by default. Perhaps you have some file extension customization in VS Code's settings file that cause problems? If not, you should be able to solve this problem by adding file extension patterns as [described](https://github.com/emilast/vscode-logfile-highlighter#file-associations) in the readme.

For example, I have this in my settings so that file extensions that contain (but not necessarily ends with) "log" are treated as log files:

```json
"files.associations": {
    "log*": "log"
},
```

If you experiment with the pattern you should be able to make it work. Try with `"*log"` or `"txt.log"` for example.
