### ISSUE TITLE
Feature request: support files with regex `*log*.txt` as filename as well

### ISSUE THREAD

**Issue by j-lakeman** [emilast/vscode-logfile-highlighter#572]
Not so rare logs are actually not `.log` files, but `.txt` or even other file endings.
However, almost all of them have “log” somewhere in their filename e.g. `eventlogs.txt`. IMHO it would make sense to look not only for `.log` as a file ending but also for the `*log*.txt` pattern and activate the extension upon those filenames also.
See also https://github.com/emilast/vscode-logfile-highlighter/issues/465#issuecomment-1613825274 how this can be manually achieved.

Great extension nevertheless! Love it!

**Comment by emilast** [comment]
It's documented [here](https://marketplace.visualstudio.com/items?itemName=emilast.LogFileHighlighter&ssr=false#user-content-file-associations) how to override file name patterns and since it's easy to extend the file type associations I think I'll leave the default as it is so as to not interfere with peoples' other file associations.
