### ISSUE TITLE
Column based pattern

### ISSUE THREAD

**Issue by raze92** [emilast/vscode-logfile-highlighter#77]
Hey,

is it possible to add a pattern for customize specific columns? When I have the following line in a logfile:

20190802T105024.638, Banana, INFO, message
20190802T105025.132, Apple, ERROR, Error message

Now I want to change the Color of the second column, in this case 'Banana' and 'Apple'. Is this possible already? When not, it would be good If i can color the text based on the columns separated with special characters.

Cheers

**Comment by emilast** [comment]
There is no explicit support for column based highlighting in CSV files or similar, but you can probably get creative with custom highlighting expressions and positive and negative lookbehind and lookahead expressions.

Here's an example that will highlight the second column in your example:

```
{
    "logFileHighlighter.customPatterns": [
        {
            "pattern": "(?<=(\\d{8}T\\d{6}.\\d{3},))[^,]*",
            "foreground": "yellow"
        }
    ]
}
```
This might look complicated if one is not experienced with regular expressions, but what it does is this:

* It first matches the date on the beginning of a line with a positive lookbehind expression: `(?<=(\\d{8}T\\d{6}.\\d{3},))`
* Then it matches all characters up to the next comma: `[^,]*` so that they are colored.

The result:

![image](https://user-images.githubusercontent.com/2369639/63102834-2474e000-bf7c-11e9-8721-8dc2b356ef86.png)

To color the second column, and a pattern for a single column (`[^,]*`) to the lookbehind expression: `(?<=(\\d{8}T\\d{6}.\\d{3},[^,]*,))`
Result:
![image](https://user-images.githubusercontent.com/2369639/63102912-55551500-bf7c-11e9-9e2c-37256d09c782.png)

Note that you can add several patterns to the **logFileHighlighter.customPattern** configuration to render different columns in different colors.

Hope this helps.

**Comment by raze92** [comment]
Thank you, that works perfectly!
