### ISSUE TITLE
Support Android logcat

### ISSUE THREAD

**Issue by naseer** [emilast/vscode-logfile-highlighter#81]
The date in Android logcat has the following format

```
09-05 03:17:59.168   589   589 I vold    : Vold 3.0 (the awakening) firing up
09-05 03:17:59.169   589   589 D vold    : Detected support for: ext4 f2fs vfat
```

**Comment by emilast** [comment]
This is the coloring i get for the above lines:

![image](https://user-images.githubusercontent.com/2369639/87546224-7ef54f80-c6a9-11ea-935b-ded0ef24d5ea.png)

The date format is not recognized since it's not complete (year is missing), but time calculation works anyway since it picks up the time of day.

I suspect that you'd also like the log level characters to be highlighted. There is already support when the log level is written with a slash, e.g. "E/" but I've thought of this and will add support single character log levels as well.

**Comment by naseer** [comment]
Thanks for the fix!
